name: Publish Docker image
on: [workflow_dispatch]
env:
  IMAGE_NAME: image
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file aspnet-mvc-docker/Dockerfile --tag $IMAGE_NAME
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: richardpoulson/aspnet-mvc-docker
          tag_with_ref: true
